### ISSUE TITLE
State Progress Bar can not have more than four state

### ISSUE THREAD

**Issue by okisetiawan0101** [kofigyan/StateProgressBar#1]
How to make State Progress Bar with more than 4 state?

**Comment by kofigyan** [comment]
This feature will be added in version 0.0.2 of StateProgressBar. Version
0.0.2 coming soon.

**Comment by Nielssg** [comment]
Could you please add it? I really need it!

**Comment by kofigyan** [comment]
Hi @okisetiawan0101  and @Nielssg , 
    Version 0.0.2 of the library is now officially released. You can now add a fifth state to your project.
