### ISSUE TITLE
Setting width match_parent

### ISSUE THREAD

**Issue by ghost** [kofigyan/StateProgressBar#12]
Hey when I'm settings width match parent (or any exact value) it leaves huge padding on both sides.
Is there any way to change it?

**Comment by kofigyan** [comment]
Hi @kestasvenslauskas , the implementation of the onMeasure method in the library enforces consistent results in all cases. The width is calculated at this line :  `int width = MeasureSpec.getSize(widthMeasureSpec);`
    You can share your codes with me or just cross-check your codes.
