### ISSUE TITLE
Font Issue 

### ISSUE THREAD

**Issue by a-najar** [kofigyan/StateProgressBar#22]
how to add custom font for text and please can you make the text position is flexible to top or bottom

**Comment by kofigyan** [comment]
These features can be done. Currently working on some new features and l will consider add these requests to it. So expect it in the next version release which l believe is very soon.

**Comment by a-najar** [comment]
@kofigyan thank you if u please can release it soon coz my app will be released in the next few days thanks 🥇

**Comment by kofigyan** [comment]
Ok @geniusforapp. I am working hard to expedite the release of new features. I will keep you posted on this.

**Comment by a-najar** [comment]
@kofigyan Any update please 👍

**Comment by kofigyan** [comment]
Hi @geniusforapp , ability to add custom fonts to state items and state description feature completed now. Please consult the docs for details(quick intro at Readme.md main page). Apologies. I should have introduced this feature earlier.

**Comment by anajar** [comment]
@kofigyan thanks bro i will update the lib , one more thing can u update also the position of the font to the top or bottom

**Comment by kofigyan** [comment]
Thank you @anajar for the positive feedback. With regard to your feature request(ie.  position of the font to the top or bottom) l am assuming you mean ability to move state number position up or down. Let me if my understanding of your question is correct.

**Comment by anajar** [comment]
@kofigyan no i mean the text it self of the status let's say progress one text now its in the bottom if there is a method that can help me to move it top or chose between top or bottom or start or end of the dot

**Comment by kofigyan** [comment]
![custom_font_spb](https://user-images.githubusercontent.com/1220772/39086176-bd0f0f92-4585-11e8-8184-797b36c882ce.jpg)

If we take this screenshot as an example. You mean ability to move the descriptions["Details", "Status", "Photo", "Confirm"]  to the top/bottom etc.  right ?

**Comment by a-najar** [comment]
@kofigyan yes this what he mean
