### ISSUE TITLE
is it possible can set click event at circles?

### ISSUE THREAD

**Issue by ajayqualwebs** [kofigyan/StateProgressBar#24]

**Comment by kofigyan** [comment]
Please can you describe the scenario or possibly the use case for such a feature.

**Comment by ajayqualwebs** [comment]
I want when i click on mStateNumber of circle so get value of clicked draw circle.

**Comment by ajayqualwebs** [comment]
Give me any suggestion it's important.

**Comment by yatindeokar** [comment]
i also want the same feature so that i can change stage on onClick event of circle.

**Comment by ajayqualwebs** [comment]
So did you get something?

**Comment by kofigyan** [comment]
Hi @ajayqualwebs , please sorry for the delay. I have started exploring the possible solution to your request. I am working on it alongside another feature request so please give me at most a week to get back to with an answer. I am currently exploring ways and means of getting support from the community so l can concentrate much of my time on adding many of the feature requests.

**Comment by ajayqualwebs** [comment]
Ok thanks for this improvement.

**Comment by kofigyan** [comment]
Hi @ajayqualwebs   and @yatindeokar  the features are fully implemented now and available to the general public. How to use : 
1. Add to build.gradle 
`implementation 'com.kofigyan.stateprogressbar:stateprogressbar:0.0.8'`

2. Add the following codes 
`stateProgressBar.setOnStateItemClickListener(new OnStateItemClickListener() {
            @Override
            public void onStateItemClick(StateProgressBar stateProgressBar, StateItem stateItem, int stateNumber, boolean isCurrentState) {
                Toast.makeText(getApplicationContext(), "state Clicked Number is " + stateNumber, Toast.LENGTH_LONG).show();
                
            }
        });`

**Comment by kofigyan** [comment]
I will be working on full documentation tomorrow after l finish lecturing my students.

**Comment by yatindeokar** [comment]
Thank you so much for this change.  now its amazing.

**Comment by ajayqualwebs** [comment]
Thank You very much, for this wonderful library which I already implement with my project, but it's become more reliable for other.
Thanks Again.

**Comment by kofigyan** [comment]
You are welcome @ajayqualwebs.

**Comment by ajayqualwebs** [comment]
Hello Kofigyan/Stateprogressbar
I have the implement new thing with it the user can create dynamically the
number of states.

If you want of I can share my code with you.

Thank You

**Comment by kofigyan** [comment]
Thank you @ajayqualwebs. Please do send me a pull request.

 - Kofi.
