### ISSUE TITLE
how to add more than 4 states?

### ISSUE THREAD

**Issue by xellDart** [kofigyan/StateProgressBar#25]
i need nine states for this

**Comment by kofigyan** [comment]
Hi @xperiafan13-rom , thanks for reaching out. You can currently add a maximum of five states. I am currently working on the ability to add infinite(N) number of states. This feature will be available soon. I am considering the possibility of giving you an early exclusive preview(Not full features but a working solution). I will keep you posted on that.

**Comment by rohitgarg29** [comment]
You need to make changes like below. Till the time, kofigyan completes the next version, you can use below work around.

public enum StateNumber {
        ONE(1), TWO(2), THREE(3), FOUR(4), FIVE(5), SIX(6), SEVEN(7), EIGHT(8);
        private int value;

        StateNumber(int value) {
            this.value = value;
        }

        public int getValue() {
            return value;
        }
    }

**Comment by sudarshaana** [comment]
If your work has finished of adding more then 5 states, please commit changes.

**Comment by shadygoneinsane** [comment]
someone plz fork and fix this !!

**Comment by Mansourx** [comment]
need to use the same Lib for 7 states!
