### ISSUE TITLE
How to make is Right To Left (RTL)?

### ISSUE THREAD

**Issue by Inzimam-Tariq** [kofigyan/StateProgressBar#28]
I'm developing app in Arabic so I need it to to show step number from RTL like 4, 3, 2, 1 but currently its  LTR like 1, 2, 3, 4. How can I do that?

**Comment by kofigyan** [comment]
I will work on this within the week and update you.

**Comment by Inzimam-Tariq** [comment]
Thanks

**Comment by kassemitani** [comment]
any update on the Right to Left ? for arabic

**Comment by kofigyan** [comment]
@Inzimam-Tariq  and @kassemitani  is done. I am just preparing to upload it soon. See screenshots below :
 
![screenshot_2018-03-12-15-08-43](https://user-images.githubusercontent.com/1220772/37304097-90b4178e-2628-11e8-9e2b-57f6227c7d18.png)

![screenshot_2018-03-12-15-08-25](https://user-images.githubusercontent.com/1220772/37303984-1fb33344-2628-11e8-9686-19f0f66101fc.png)

**Comment by kofigyan** [comment]
Hi @Inzimam-Tariq and @kassemitani ,please can you look at the the implementation of the description of each state and confirm to me whether is consistent with Arabic style of writing.

`    String[] descriptionData = {"Details", "Status", "Photo", "Confirm" , "Done"};
`
`@Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        stateProgressBar.setStateDescriptionData(descriptionData);
    }`

English(Ascending)

![screenshot_2018-03-14-14-32-43](https://user-images.githubusercontent.com/1220772/37449731-58edca50-2823-11e8-9a0e-d6f49d96a92a.png)

Arabic (Descending)

![screenshot_2018-03-14-14-32-10](https://user-images.githubusercontent.com/1220772/37449766-7bf49394-2823-11e8-841b-eff324900742.png)

**Comment by kassemitani** [comment]
great job @kofigyan , is it possible to allow to add any drawable inside the circle shape??  Instead of numbers and checkmark.

**Comment by kofigyan** [comment]
Thanks @kassemitani for the feedback. I will look into the drawable inside the circle shape request and give you a feedback soon.

**Comment by kofigyan** [comment]
Hi @kassemitani , to clarify my question, what should be the proper Arabic representation of this code : 

`String[] descriptionData = {"Details", "Status", "Photo", "Confirm" , "Done"};`

Please is it 1 or 2 ?  : 

1. 
![screenshot_2018-03-15-08-43-18 1](https://user-images.githubusercontent.com/1220772/37453338-4e6323a8-282f-11e8-98df-6aaadb47e58d.png)

2.
![screenshot_2018-03-15-08-38-50](https://user-images.githubusercontent.com/1220772/37453366-5c67bb58-282f-11e8-894f-8d428bb6b160.png)

**Comment by kassemitani** [comment]
2 is correct

**Comment by kofigyan** [comment]
Thank you @kassemitani  for the feedback. I will finish with these features and quickly look into your feature(drawable inside the circle shape) request.

**Comment by kassemitani** [comment]
Thank you @kofigyan for your awesome work! Let us know when you going to commit changes.

**Comment by kofigyan** [comment]
Hi @kassemitani , l will make all the features available to the public most likely this week. This round of updates cover many of the feature requests from users. I am putting the finishing touches to it.

**Comment by kofigyan** [comment]
Hi @kassemitani  and @Inzimam-Tariq the features are fully implemented now and available to the general public. How to use : 
1. Add to build.gradle 
`implementation 'com.kofigyan.stateprogressbar:stateprogressbar:0.0.8'`

2.  Add attribute  in xml file
`app:spb_stateNumberIsDescending="true"`

Eg.
`
    <com.kofigyan.stateprogressbar.StateProgressBar
        android:id="@+id/state_progress_bar"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:spb_currentStateNumber="three"
        app:spb_maxStateNumber="four"
        app:spb_stateNumberIsDescending="true" />`

3. Or add in java code

    `stateProgressBar.setStateNumberIsDescending(true);`

**Comment by kofigyan** [comment]
I will be working on full documentation tomorrow after l finish lecturing my students.

**Comment by Inzimam-Tariq** [comment]
Good to know You have fixed it, I will use it in my project. thanks

**Comment by kofigyan** [comment]
You are welcome @kassemitani .
