### ISSUE TITLE
Changing of Color, size,Line Thickness returns back to it initial color after changing the device orientation or pressing back button

### ISSUE THREAD

**Issue by michygeek** [kofigyan/StateProgressBar#31]
Hello, I need your reply on this behavior ASAP, i think there should be a save button to keep those setting remain in it state or is the behavior a bug?

**Comment by kofigyan** [comment]
It shouldn't be. Please let me look into  it quickly and give you a
feedback.

**Comment by kofigyan** [comment]
Hi @tykees , issue resolved in the new version (1.0.0) release. Please update your library to reflect this fix.

**Comment by michygeek** [comment]
oK...Thanks, I will
