### ISSUE TITLE
Can't use this library

### ISSUE THREAD

**Issue by michael-winkler** [kofigyan/StateProgressBar#34]
Why can I not download the jar file from jitpack ?
I tried a lot of things without succes.

I need a working aar file.
Is there anything broken on master?

**Comment by michael-winkler** [comment]
https://jitpack.io/com/github/kofigyan/StateProgressBar/d6e2e4e794/build.log

> Build starting...
Start: Sun Jul 15 14:20:47 UTC 2018
Git:
fatal: No names found, cannot describe anything.
commit d6e2e4e794b31ef2ea8e4509ec80a191bb567696
Author: kofigyan 
Date:   Wed Jun 20 07:08:55 2018 +0000

    Saving states and version 1.0.0 released


Run gradle build
Gradle build script
Found gradle version: 4.1.
Using gradle wrapper
Getting tasks: ./gradlew tasks --all
0m0.000s

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Adding maven plugin
Found android library build file in stateprogressbar
Running: ./gradlew clean -Pgroup=com.github.kofigyan -Pversion=d6e2e4e794 install
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
EXIT_CODE=0
2018-07-15T14:20:49.934413272Z
Exit code: 0
No build artifacts found

**Comment by kofigyan** [comment]
Hi @NmdOfficial , please let me check it out and give you a feedback within the week.

**Comment by michael-winkler** [comment]
@kofigyan thanks for your answer.
Yeah please look into it.
The lib looks really nice and I want to use it in a public app builder (makeroid.io)

But as you can see I have problems to get the aar from this lib.

**Comment by michael-winkler** [comment]
Hi @kofigyan 
Any news on it?
Else can you send me a working aar file of the lib?

**Comment by kofigyan** [comment]
Hi @NmdOfficial , please sorry for the delay in reply. I am currently on a project here so l plan on finishing it up this weekend.

> Else can you send me a working aar file of the lib?

=> I will quickly look at it today and give you a feedback.

**Comment by michael-winkler** [comment]
Allright thank you very much @kofigyan :)

**Comment by kofigyan** [comment]
I have the aar file. I am not able to upload here(format not supported). Please can l send it to you through any other means ? email etc.

**Comment by michael-winkler** [comment]
Yes of course:
nmdofficialhelp@gmail.com 

Thank you :)

**Comment by kofigyan** [comment]
Sent. Please let me know if it worked for you.

**Comment by michael-winkler** [comment]
I tried the aar you send:
java.lang.RuntimeException: Font asset not found fonts/fontawesome-webfont.ttf

For what do we need this font?
Can we not use a default android font without a extra font file ?

**Comment by michael-winkler** [comment]
Any news again @kofigyan ?

**Comment by kofigyan** [comment]
Hi @NmdOfficial , please forgive me for the apparent delay. I was a little tied down over the weekend.

> For what do we need this font?

I think the name fontawesome could be a little misleading. Probably fontawesome extract could be the right nomenclature(naming), because is just a small extract from font awesome for the state completed sign(correct/check sign).

> Can we not use a default android font without a extra font file ?

I wouldn't say is impossible. Just that given what l wanted to achieve with the library(showing state completed sign without any image pixelation issues) that was an apt and immediate solution. But l will not rule out other possible means of achieving it(the truth is l have look at other libraries trying to achieve the same goal via other means and l was not so impressed with the results).

I will examine why the .ttf was not included in the .aar file generated. Rebuild the library's .aar file to make sure it is included and update you.

**Comment by michael-winkler** [comment]
Allright.

I looked into the aar and the font is there.
I added the aar like normal way of doing it.
After starting the app I got the crash and it tells me that the font was not found.

What about to add the font in the normal assets folder and not in the "font" folder?
Maybe it is a good try to catch the issue.

By the way, have you found the problem why master not works?

**Comment by kofigyan** [comment]
Hi @NmdOfficial , there is definitely workarounds for this. I will look at it today and get back to you with the results.

> What about to add the font in the normal assets folder and not in the "font" folder?

I will explore this solution today and give you the feedback

> By the way, have you found the problem why master not works?

I will look into this today as well.

**Comment by michael-winkler** [comment]
Hello @kofigyan Any news about the progress ?
