### ISSUE TITLE
Cannot make the Description text in Two Lines...

### ISSUE THREAD

**Issue by aneeshkr-me** [kofigyan/StateProgressBar#4]
I wanted to make the description text in two lines. I tried passing '\n' within the text but it was not making any difference

**Comment by kofigyan** [comment]
This looks like a good idea. I will consider adding this feature in future updates. In my opinion it should be possible to implement such a feature with moderate effort.

**Comment by Adnan-addi** [comment]
i am having the same issue , i want to display the text in two lines , how can i achieve this . \n doesn't work.

**Comment by kofigyan** [comment]
Hi @itzAneesh and @Adnan-addi , ability to add multiline description to state descriptions completed now. Check the docs(Quick intro at Readme,md page/main page). Options to justify description texts, specify spacing for description and set maximum description line included in this update.  Thank you all for your patience.

**Comment by Beevish** [comment]
hey can you add this ability in your xamarin library also.
