### ISSUE TITLE
can't set a fixed height for this view, why?

### ISSUE THREAD

**Issue by philadelphia** [kofigyan/StateProgressBar#42]

**Comment by kofigyan** [comment]
Hi @philadelphia , use :
`setStateSize(float)`  
or
`<com.kofigyan.stateprogressbar.StateProgressBar
android:layout_width="wrap_content"
android:layout_height="wrap_content"
app:spb_descriptionTopSpaceIncrementer="2dp"
app:spb_stateDescriptionSize="20sp"
app:spb_stateLineThickness="10dp"
app:spb_stateSize="40dp"
app:spb_stateTextSize="15sp" />`

Please check README.MD file or wiki for further details.
