### ISSUE TITLE
Full Descending order progress?

### ISSUE THREAD

**Issue by Sytehk** [kofigyan/StateProgressBar#47]
Hello, please is it possible for the circle progress to be in descending order as well and not just the numbers? i mean i want the progress to be in a count down fashion like it should start filling bar from 4,3,2,1 in that order. is this possible?

**Comment by kofigyan** [comment]
Hi Sytehk, please  is possible. Just use app:spb_stateNumberIsDescending="true" . Sorry for the late in reply.

**Comment by kofigyan** [comment]
Also add in xml  
app:spb_animateToCurrentProgressState="true"
