### ISSUE TITLE
I only get this error whenever I add this library

### ISSUE THREAD

**Issue by fayazara** [kofigyan/StateProgressBar#5]
HI I get this error when I add the library in my app java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/BuildCompat;

**Comment by kofigyan** [comment]
Hi Fayaz, these two [#1](http://stackoverflow.com/questions/25430551/noclassdeffounderror-failed-resolution-of-landroid-support-v7-appcompat-rstyl)  [#2](http://stackoverflow.com/questions/39601370/java-lang-noclassdeffounderror-failed-resolution-of-landroid-support-v4-os-bui) from StackOverflow shows that this error is not likely from this library. Maybe l can help if l see some codes.
