### ISSUE TITLE
StateProgressBar is overdrawing

### ISSUE THREAD

**Issue by connyduck** [kofigyan/StateProgressBar#8]
I noticed StateProgressBar is drawing the foreground color over the background color.
This is
1. visually noticeable on low resolutions - see attached image - top is current version, bottom is how it should look, black background color
2. bad for performance because drawing the background is not necessary

you can fix it yourself if you want, but I can also send you a pull request^^
Thanks for the cool library, it will soon be used in our 50k users app!

![comparison](https://cloud.githubusercontent.com/assets/10157047/22902389/26fcbf08-f235-11e6-9458-1c9fada0a2a1.png)

**Comment by kofigyan** [comment]
Thank you @connyduck for the positive feedback. I will definitely look into this issue. You are warmly welcome to contribute with a pull request.

**Comment by connyduck** [comment]
Sent you a pull request! I reduced the number of draw operations quite a bit. Let me know what you think of it.

**Comment by kofigyan** [comment]
I will look into it quickly and give you a feedback. I really appreciate the contributions.

**Comment by kofigyan** [comment]
Overdraw is now fixed. Pull request accepted. I had to make some few changes to accommodate feature requests from other users.

**Comment by connyduck** [comment]
Thank you very much! The change is already live in my app!
